name = "MyExample"
uuid = "afdd91c3-b6af-42c6-98ec-9622fbb72c29"
authors = ["Sean McArdle <seanmcardle14@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
